vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    card_thumbnail:
      uri_prefix: '%cards_attachments%'
      upload_destination: '%kernel.project_dir%/public%cards_attachments%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
